function fish_prompt --description 'Write out the prompt'
    set -l last_status $status

    # Preserve a blank line between the previous command and the next prompt.
    echo

    set -l normal (set_color --reset)
    set -l status_color (set_color brgreen)
    set -l login_color (set_color yellow)
    set -l cwd_color (set_color cyan)
    set -l vcs_color (set_color magenta)
    set -l prompt_status ""

    # Since we display the prompt on a new line allow the directory names to be longer.
    set -q fish_prompt_pwd_dir_length
    or set -lx fish_prompt_pwd_dir_length 0

    # Color the prompt differently when we're root
    set -l suffix '❯'
    if functions -q fish_is_root_user; and fish_is_root_user
        if set -q fish_color_cwd_root
            set cwd_color (set_color $fish_color_cwd_root)
        end
        set suffix '#'
    end

    # Color the prompt in red on error
    if test $last_status -ne 0
        set status_color (set_color $fish_color_error)
        set prompt_status $status_color "[" $last_status "]" $normal
    end

    # Use the stable display name from the previous shell instead of macOS's
    # autogenerated machine identifier.
    set -l display_login "$USER@omphalos"
    echo -s $login_color $display_login $normal ' ' $cwd_color (prompt_pwd) $vcs_color (fish_vcs_prompt) $normal ' ' $prompt_status
    echo -n -s $status_color $suffix ' ' $normal
end
